/**
 * Settings Route
 * System configuration management
 */

const express = require('express');
const router = express.Router();
const fs = require('fs');
const path = require('path');

const SETTINGS_FILE = path.join(__dirname, '..', '..', '.env');

/**
 * Read current settings from .env file
 */
function readEnvSettings() {
    const settings = {};
    
    if (fs.existsSync(SETTINGS_FILE)) {
        const envContent = fs.readFileSync(SETTINGS_FILE, 'utf8');
        envContent.split('\n').forEach(line => {
            const trimmed = line.trim();
            if (trimmed && !trimmed.startsWith('#')) {
                const [key, ...valueParts] = trimmed.split('=');
                const value = valueParts.join('=');
                if (key && value !== undefined) {
                    settings[key.trim()] = value.trim();
                }
            }
        });
    }
    
    return settings;
}

/**
 * Write settings to .env file
 */
function writeEnvSettings(settings) {
    let content = '# AnomHome Overmind Configuration\n';
    content += '# Generated by settings panel\n\n';
    content += '# Server Configuration\n';
    content += `PORT=${process.env.PORT || 3000}\n`;
    content += `HOST=${process.env.HOST || '0.0.0.0'}\n\n`;
    
    content += '# AI Configuration\n';
    if (settings.aiProvider === 'local') {
        content += `AI_PROVIDER=local\n`;
        content += `LOCAL_MODEL_PATH=${settings.localModelPath || ''}\n`;
        content += `MODEL_CONTEXT_SIZE=${settings.modelContextSize || 4096}\n`;
        content += `LOCAL_SERVER_PORT=${settings.localServerPort || 8080}\n`;
    } else {
        content += `AI_PROVIDER=openai\n`;
        content += `OPENAI_API_KEY=${settings.openaiKey || ''}\n`;
    }
    content += '\n';
    
    content += '# File Browser Configuration\n';
    content += `FILE_BROWSER_ROOT=${settings.fileRoot || ''}\n\n`;
    
    content += '# Upload Configuration\n';
    content += `MAX_UPLOAD_SIZE=${settings.maxUploadSize || 100}\n\n`;
    
    content += '# Security\n';
    content += `SECRET_KEY=${settings.sessionSecret || 'your_secret_key_here'}\n`;
    
    fs.writeFileSync(SETTINGS_FILE, content, 'utf8');
}

/**
 * GET /api/settings
 * Get current settings
 */
router.get('/', (req, res) => {
    try {
        const envSettings = readEnvSettings();
        
        const settings = {
            aiProvider: envSettings.AI_PROVIDER || 'openai',
            openaiKey: envSettings.OPENAI_API_KEY || '',
            localModelPath: envSettings.LOCAL_MODEL_PATH || '',
            modelContextSize: parseInt(envSettings.MODEL_CONTEXT_SIZE) || 4096,
            localServerPort: parseInt(envSettings.LOCAL_SERVER_PORT) || 8080,
            fileRoot: envSettings.FILE_BROWSER_ROOT || '',
            maxUploadSize: parseInt(envSettings.MAX_UPLOAD_SIZE) || 100,
            sessionSecret: envSettings.SECRET_KEY ? '****' : '' // Hide actual secret
        };
        
        res.json(settings);
        
    } catch (err) {
        console.error('[Settings] Get error:', err.message);
        res.status(500).json({ error: 'Failed to load settings' });
    }
});

/**
 * POST /api/settings
 * Update settings
 */
router.post('/', (req, res) => {
    try {
        const {
            aiProvider,
            openaiKey,
            localModelPath,
            modelContextSize,
            localServerPort,
            fileRoot,
            maxUploadSize,
            sessionSecret
        } = req.body;
        
        // Validate required fields based on AI provider
        if (aiProvider === 'openai' && !openaiKey) {
            return res.status(400).json({ error: 'OpenAI API key is required' });
        }
        
        if (aiProvider === 'local' && !localModelPath) {
            return res.status(400).json({ error: 'Local model path is required' });
        }
        
        // Write settings to .env file
        writeEnvSettings({
            aiProvider,
            openaiKey,
            localModelPath,
            modelContextSize,
            localServerPort,
            fileRoot,
            maxUploadSize,
            sessionSecret
        });
        
        res.json({
            success: true,
            message: 'Settings saved successfully. Restart the server to apply changes.'
        });
        
    } catch (err) {
        console.error('[Settings] Update error:', err.message);
        res.status(500).json({ error: 'Failed to save settings' });
    }
});

module.exports = router;